# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f249702e9cd122cbef1b35779a43b4c1086473a1be473d4ef10828ac6bc505cc5393eb6e438ad92cb030f5a62eee78e9b95bc69511c774288ce0570185c2986

test:
  secret_key_base: 5dda42c2d3bd8b3a1349809d560eb004a5d90a8506a057c317b4f9a4eee2c74595e50250cfbc8ab54ec9bf8c8d443564faf5fef82d53e68391eb83988b0066d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
